### ISSUE TITLE
[DevOps] [Ask] Запрос на РАСПРЕДЕЛЕННЫЙ МОНОЛИТ(зачеркнуто)

### ISSUE THREAD

**Issue by AlexBimlnk** [book-hub-umsp/book-hub-api#108]
Запрос на ~РАСПРЕДЕЛЕННЫЙ МОНОЛИТ~ новый компонент

Кодовая база становится достаточно большой и ориентироваться в ней не шибко удобно. Согласно драфту архитектуры предполагалось в будущем рассматривать микросервисную/сервисноориетированную архитектуру.
Выделение домена обсуждений (topics) хорошо вписывается в отдельную сферу/компонент.
Разработка и поддержка домена обсуждений в отдельном компоненте может принести:

- Упрощение кодовой базы
- Уменьшение мердж конфликтов и независимости разработки
- Изоляция проблем
- Независимость домена и его развитие
- Это позволит более гранулярно горизонтально масштабироваться 
- Наличие отдельной схемы/бд упростить схему основной БД

Основные сложности:

- Затраты инфраструктурных ресурсов
- Усложнение DevOps процессов
- Усложнение ручного/сквозного тестирования

В целом не обязательно создавать отдельную базу, но если ресурсы могут нам это позволить, я бы хотел вынести идею о том, чтобы создать отдельный компонент, который будет обслуживать дискуссионную доменную область приложения.

@wi1sp  Реально ли это? 

@Tigeroff2002 @WillzzArt  Что думаете?

FYI @xErkAy

**Comment by wi1sp** [comment]
@AlexBimlnk 
по ресам сейчас на ключевые сервисы (бек и база) выделена квота 1гб оперативы и 2ггц процесора
![image](https://github.com/user-attachments/assets/685ee00d-6b7b-4f1f-898d-4592fe7f3915)
хз много это или мало
но на самой машине сейчас вообще ниче не юзается
![image](https://github.com/user-attachments/assets/7b899b70-fb5d-4fd7-8086-01f7eacd917d)

теоритически если хвоты максимально поужимать то пару доп джобов хватит

**Comment by wi1sp** [comment]
но так вообще не понятно на скок выделенной квоты сервисам хватит

**Comment by AlexBimlnk** [comment]
Ну из того, что я вижу мы совсем чуть-чуть потребляем. 
![изображение](https://github.com/user-attachments/assets/cc5fb1e2-8ba6-4d80-8366-7612cbddefc9)
В теории на другой сервис можно резануть 300МБ + 0.5ГГЦ и должно быть вполне ок.
В любом случае сейчас нагрузки нет и у нас большой запас. Сами реквесты

**Comment by Tigeroff2002** [comment]
Можно думать потихоньку над разделением функционала под разные системы
Но надо подумать только в каком виде будет происходить общение между сервисами - и подумать над тем, можем ли мы в будушем проводить интеграционное тестирование каждого отдельного микросервиса - или ограничимся тестированием всей системы per request целиком

**Comment by AlexBimlnk** [comment]
С т.з. итеграционного тестирования - оно будет легче и изоляции.
Общение пока можно сделать самым быстрым способом - http rest.
Оба варианта архитектуры позволяют проводить и сковзное и интеграционное тестирование.

**Comment by AlexBimlnk** [comment]
Решили что делаем (Делай делай делай, а когда не делали?)

**Comment by AlexBimlnk** [comment]
Решили что делаем (Делай делай делай, а когда не делали?)
