### ISSUE TITLE
[Book/Content] Уточнить хранение текста в главах номерами строк

### ISSUE THREAD

**Issue by Tigeroff2002** [book-hub-umsp/book-hub-api#126]
Чтобы можно было как то понимать в будущем, к какой строке главы вводятся (предлагаются) изменения и чтобы в том числе на фронте было это видно - и после загрузки на бэк эта информация как то сохранялась - есть вариант делать это прямо храня для каждой главы текст построчно - запоминая номер для каждой строки.
Благодаря этому поиск различий по идее сведется к проверке конкретных строк, которые прислал фронт в запросе

Я предлагаю такой вариант:

```
CREATE TABLE chapter_rows_links (
     id BIGINT GENERATED ALWAYS AS IDENTITY,
     chapter_id bigint not null,
     row_id int not null,
     content text not null default '\n',
     CONSTRAINT "fk_chapters_rows_links_chapter_id"
     FOREIGN KEY (chapter_id) REFERENCES chapters (id) ON DELETE CASCADE
);

ALTER TABLE chapters ADD COLUMN rows_count INT DEFAULT 0;

CREATE OR REPLACE FUNCTION update_chapter_rows_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE chapters
        SET rows_count = GREATEST(rows_count, NEW.row_id)
        WHERE id = NEW.chapter_id;

    ELSIF TG_OP = 'DELETE' THEN
        UPDATE chapters
        SET rows_count = rows_count - 1
        WHERE id = OLD.chapter_id;

        UPDATE chapter_rows_links
        SET row_id = row_id - 1
        WHERE chapter_id = OLD.chapter_id AND row_id > OLD.row_id;

    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_chapter_rows_count
AFTER INSERT OR DELETE ON chapter_rows_links
FOR EACH ROW
EXECUTE FUNCTION update_chapter_rows_count();
```

**Comment by Tigeroff2002** [comment]
Триггер весьма примерный, тут надо подумать, как лучше сделать, так как существуют варианты, когда условно изменяется какая то строка в середине/либо вставляются строки по середине главы - это нужно бы контролировать по целостности не только в домене, но и в хранилище

**Comment by Tigeroff2002** [comment]
Также я думаю не очень оптимизированно будет сразу посылать 40000 строк главы пользователю - по этому благодаря строкам можно придумать какую то около пагинацию или как говорили на фронте - последовательную подгрузку остального текста

**Comment by AlexBimlnk** [comment]
И зачем это?? Проектирование работы дифов - есть отдельная задача на ресерч. И никто не будет хранить строки текста в БД - это не жизнеспособно.

**Comment by AlexBimlnk** [comment]
Все это обсуждается и делается в задаче #106

**Comment by Tigeroff2002** [comment]
Дифы это немного другое, это уже последствие того что мы что то в строках главы можем изменять и надо это как то сравнивать
Ну даже если не строки - то все равно придётся хранить хотя бы какие-то абзацы, и по ним смотреть
