### ISSUE TITLE
[Book\Repository] Books list pagination

### ISSUE THREAD

**Issue by Tigeroff2002** [book-hub-umsp/book-hub-api#46]
Необходимо добавить возможность получения списка книг (не только одной книги, как есть сейчас)
Список книг может быть например у пользователя (как его написанные) - либо пока просто список всех добавленных книг. Из книг нужно получать при этом только title, genre и author_id

Для этого списка нужно предусмотреть возможность запросов с применением пагинации

**Comment by AlexBimlnk** [comment]
Нужно учитывать, что получая список книг, нам не нужно доствать всю информацию о них. Названия, жанра и id автора будет достаточно.
И надо эту объемную работу в несколько задач разбить. И для начала сделать просто получение книг с пагинацией.
