### ISSUE TITLE
Перенести миграцю в другую папку

### ISSUE THREAD

**Issue by wi1sp** [book-hub-umsp/book-hub-api#99]
- [x] перенести миграцию в папку `migrations`
- [x] добавить `BEGIN;` `COMMIT`
- [x] проверить что она работает

**Comment by wi1sp** [comment]
речь про миграцию отсюда #80

**Comment by wi1sp** [comment]
@book-hub-umsp/backendteam

**Comment by AlexBimlnk** [comment]
@wi1sp лучше сделать отдельным пром. И еще надо порядок миграций поменять (сначала юзер, потом книги). И сделать foreign key уже в миграции с книгами. Без alter table в user миграции

**Comment by wi1sp** [comment]
@AlexBimlnk это типа мне делать?

**Comment by AlexBimlnk** [comment]
@wi1sp ну хотелось бы да
